name: CI - On Pull Request

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    name: Testing Application
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
          check-latest: true

      - name: Installing Dependencies
        run: yarn

      - name: Running Tests
        run: yarn test

      - name: Building Application
        run: yarn build
